# Ch4 numpy套件(numeric python)
## 為甚麼需要numpy？
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較為正常，python數字儲存不正確
* numpy節省記憶儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [1]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#numpy套件的ndarray型態，提供element-wise的操作 element-wise意思是最每一個元素都進行操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape,'筆')#ndaary的形狀  顯示多少筆資料
print(a.dtype)#顯示資料的型態
print(a.ndim) #顯示幾維度

<class 'numpy.ndarray'>
(5,) 筆
int32
1


In [18]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((2,4,2))) #產生2X4X2得三維陣列
print(np.empty((2,4))) #產生2X4得二維陣列
print(np.arange(10)) #產生0~9得陣列

[0. 0. 0. 0. 0. 0.]
[[[6.95171702e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [8.62278585e-312 0.00000000e+000]]

 [[0.00000000e+000 8.62310034e-312]
  [0.00000000e+000 8.62278585e-312]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 8.62278585e-312]]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.04736351e-321 7.56587583e-307 1.37961302e-306]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [21]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])   #第0個
print(my_array[0:5]) #顯示出0到4的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


## 二維資料取值

In [23]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)]) #顯示0~9的二維陣列
print(my_2d_array)
print(my_2d_array[1,:]) #顯示第二欄的全部值
print(my_2d_array[:,1]) #顯示第一、二欄的第2個值
print(my_2d_array[1,1]) #顯示第二欄的第二個值

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [26]:
my_array=np.arange(10)
print(my_array)
print(my_array.shape) #多少筆資料
my_2d_array=my_array.reshape(2,5) 
print(my_2d_array)
print(np.arange(0,100).reshape(10,10))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [31]:
b=np.array([56, 8, 19, 14, np.nan])
print(b)

[56.  8. 19. 14. nan]
